import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Header from "~/components/Header";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function HeaderLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<>
			<Header userRole="traveler" />
			{children}
		</>
	);
}
